name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: ["published"]    

jobs:
  build_image:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Lint Dockerfile with Hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        no-fail: true
        
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag android_fastlane$(date +%s)

    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
        format: table
        exit-code: 1
        ignore-unfixed: true
        
    - name: Generate SBOM
      uses: anchore/sbom-action@v0.15.2
      with:
        image: ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
        format: spdx-json
        output-file: sbom.spdx.json

  push_image:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Github Container Registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN}}
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: |
          ghcr.io/${{ github.repository }}
          
    - name: build and push docker image
      uses: docker/build-push-action@v6
      id: push
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tag }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ghcr.io/${{ github.repository }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
