name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: ["published"]    

jobs:
  build_image:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag android_fastlane$(date +%s)

  push_image:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    
    - name: Log in to Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN}}

    - name: Build and tag docker image
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/android_fastlane
        TAG=${{ github.event.release.tag_name }}
        docker build . -f Dockerfile -t $IMAGE_NAME:$TAG

    - name: Push Docker image to GHCR
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/android_fastlane
        TAG=${{ github.event.release.tag_name }}
        docker push $IMAGE_NAME:$TAG
      
